refact: UserinfoSlice로 합치기
GIST-Petition-Site-Project/GIST-petition-web pull request #258
Opened 2022-02-26 15:32 UTC by choi2021

## 개요

findPasswordSlice.ts와 registerSlice.ts의 코드가 회원약관 버튼의 이슈를 해결하면서 거의 동일해졌습니다.
재사용하기 위해 둘을 통일하겠습니다.

## 상세 설명

1. Register Slice와 findPassword Slice를 삭제했습니다.
2. 각 페이지에 새로운 userInfoSlice를 적용했습니다. 

## 기타

Close #255

2022-02-26 15:38 UTC, leejimin-gist approved these changes
👍

2022-02-26 16:26 UTC, gpgun0 commented
<img width="568" alt="스크린샷 2022-02-27 오전 1 25 54" src="https://user-images.githubusercontent.com/65757344/155850814-af44389e-9845-4528-bc1a-662c157ada7a.png">

비밀번호 찾기 후 바로 회원가입 페이지를 들어가면 다음과 같이 뜹니다 ㅜ

2022-02-26 16:29 UTC, gpgun0 requested changes
추측으로는 
slice가 통일되면서
state가 계속 유지돼서 생기는 문제 같습니다.

state를 초기화해줄 수 있나요???



리덕스 데브툴즈를 보면 상태값이 초기화되지 않는다고 나와있습니다!

<img width="1188" alt="스크린샷 2022-02-27 오전 1 33 13" src="https://user-images.githubusercontent.com/65757344/155851080-c6fba53b-b676-45d4-8bcc-1156e71b75ff.png">


해결책은
계정 만들기가 Link로 돼있는데 이를 그냥 a태그로 바꿔주면 될거 같습니다.

2022-02-26 16:52 UTC, choi2021 commented
오류 찾아주셔서 감사합니다 ㅜㅜ 그럼 얼른 수정해보겠습니다

2022-02-27 05:59 UTC, gpgun0 approved these changes

2022-02-27 09:09 UTC, merged